Angry Pickles work 5-28-2020
modified:   src/components/OrdersShipping/Completed.js
Added shipping information to include tracking number and link to shipping label

modified:   src/components/OrdersShipping/Ship.js
Added loading spinner so when "Purchase shipping" is clicked it shows result
including tracking number and link to shipping label

modified:   src/functions/createShipment.js
Created a serverless function to access the Easypost api
Function to purchase shipping from Easypost
API doc here => https://www.easypost.com/stripe-relay
Originally written in Ruby but converted to node
and https://www.easypost.com/docs/api/node#shipments

modified:   webpack.development.js
modified:   webpack.production.js
modified:   gatsby-node.js
Added new webpack.DefinePlugin({ "global.GENTLY": false }) to fix an error where require wasn't being recognized
The error was Function invocation failed: TypeError: n is not a function
Fixed according to https://github.com/netlify/netlify-lambda/issues/64
Added onCreateWebpackConfig to gatsby-node as well